# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

##### RPC configrations #####

# RPC endpoint for ethereum chain
eth_RPC_URL = "https://testnet2.matic.network"

# RPC endpoint for bor chain
bor_RPC_URL = "http://34.228.28.224:8545"


# RPC endpoint for tendermint
tendermint_RPC_URL = "http://0.0.0.0:26657"

##### Chain ID configration #####

# Bor chain ID
bor_chain_id = "15001" 


##### MQTT and Rest Server Config #####

# MQTT endpoint
amqp_url = "amqp://guest:guest@localhost:5672/" 

# Heimdall REST server endpoint
heimdall_rest_server = "http://0.0.0.0:1317" 

##### Contract Addresses #####

### Eth Chain Contracts
stakinginfo_contract = "0x0000000000000000000000000000000000000000"
stake_manager_contract = "0xF2594f62746e1769FfAEa3164fEb5A444C187b8e"
rootchain_contract = "0x0ced3563E98dF446863c8A8B1B798Dd2DCf38896"
state_sender_contract = "0x9aDa557Ba0bCA418A11EaaE36F7f7922D4899Cdf"
matic_token = "0xf25F61E749e4Cdab67E9EFABd70B229BEAaD0cF1"

### Bor Chain Contracts
state_receiver_contract = "0000000000000000000000000000000000001001"
validator_set_contract = "0000000000000000000000000000000000001000"

##### Intervals #####
child_chain_block_interval = "10000" 

## Bridge Poll Intervals 
checkpoint_poll_interval = "5m0s" 
syncer_poll_interval = "1m0s"
noack_poll_interval = "16m50s"
clerk_polling_interval = "10s" 
span_polling_interval = "5m0s" 


##### Checkpoint Length Config #####
avg_checkpoint_length = "256"
max_checkpoint_length = "1024"

##### Timeout Config #####

no_ack_wait_time = "30m0s"
checkpoint_buffer_time = "16m40s"

##### Transaction Confirmations  #####

confirmation_blocks = "6"

